### ISSUE TITLE
Concoct Roadmap

### ISSUE THREAD

**Issue by ldilley** [ConcoctLang/concoct#10]
# Concoct Roadmap

1. [x] Draft language (keywords, operators, and syntax)
2. [x] Implement lexer
3. [ ] Implement parser
4. [x] Draft opcodes/instruction set
5. [ ] Implement stack-based VM along with instruction set
6. [ ] Handle semantics, scope, strings, flow control, expression evaluation, etc.
7. [ ] Implement garbage collection
8. [ ] Implement standard library constants, data structures (lists, hashmaps, etc.), and functions
9. [ ] Implement super(classes), inheritance, and objects
10. [ ] Bonus round: implement a compiler (LLVM perhaps?)
11. [ ] Refactor, optimize, test, and re-test
